### ISSUE TITLE
source bootstrapping should be reworked

### ISSUE THREAD

**Issue by tru7** [linknx/linknx#5]
bootstrapping environment is quite old and should be reworked so it's possible to run newer versions of aclocal, automake, autoconf without problems

**Comment by 2franix** [comment]
Fixed in #6. Thanks @tru7!

**Comment by 2franix** [comment]
@tru7 Would you be kind enough to generate a "configure" script and commit it? Having configure under version control would help end user compile our master branch. I am in contact with one of them that encounters issues compiling v0.0.1.32 because of a bad mysql dependency and I think that would be a perfect fit for your recent changes  :)

**Comment by tru7** [comment]
@2franix No problem. You can merge #11, I have added all the autogenerated files in the pull request. Of course you could have done the same by just runnig the bootstrap.sh script.
Have you thought about preparing a new release number for the new source code status?

**Comment by 2franix** [comment]
I just merged #11, thanks. For sure I could have run bootstrap.sh but I was not aware of this script, sorry. And since I didn't know the exact procedure to run the autoconf suite, I preferred to ask the rescue team ;)
(And for some reason, I did not get any notification from github for your last two PR, sorry for the delay)

**Comment by 2franix** [comment]
And to answer your last question, yes, the version will be increased before the version is considered ready. It will be v1.

**Comment by tru7** [comment]
@2franix My branch worked fine but the git clone from master seems to have changed file timestamps which causes another autoreconf which unfortunately fails in my test. I think I know how to fix this, I will take care tomorrow.
How does it work for you?
